# Generated by Django 4.2.28 on 2026-02-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='new_field',
        ),
    ]
